version: '3.3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - 'pg-data:/var/lib/postgresql/mydatabase'
volumes:
  pg-data:
